
spring:
  datasource:
    name: db_ccpush  #数据库名
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC #url
    username: root  #用户名
    password: root  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动
